name: Redhill Stories
favicon: null
layout_spectrum: 0.099449627334252
typography_spectrum: 0.3255518216174096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7346302180085331
  lightness: 0.7863234635442495
  saturation: 0.5556004750542343
  rhythmicContrast: 0.4745420978870243
purpose: []
